server:
  port: 8080

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: Manager123
    url: jdbc:mysql://localhost:3306/db2023?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: com.example.demo.pojo   # 实体类位置
  mapper-locations: classpath:/mapper/*.xml   #  mapper位置
  configuration:
    map-underscore-to-camel-case: true  # 驼峰转换

logging:
  file:
    name: log/log.log   # 输出日志文件目录（在项目根目录）
  level:
    root: info
    wuhobin: debug

